basePath: /
definitions:
  controllers.CreateTaskRequest:
    properties:
      description:
        type: string
      due_date:
        description: user passes string in YYYY-MM-DD
        example: yyyy-mm-dd
        type: string
      status:
        enum:
        - pending
        - in_progress
        - completed
        type: string
      title:
        maxLength: 100
        type: string
    required:
    - description
    - due_date
    - title
    type: object
  controllers.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  controllers.RegisterRequest:
    properties:
      password:
        minLength: 4
        type: string
      username:
        minLength: 3
        type: string
    required:
    - password
    - username
    type: object
  controllers.UpdateTaskRequest:
    properties:
      description:
        type: string
      due_date:
        description: string from client
        example: yyyy-mm-dd
        type: string
      status:
        description: optional
        enum:
        - pending
        - in_progress
        - completed
        type: string
      title:
        maxLength: 100
        type: string
    required:
    - description
    - due_date
    - title
    type: object
  models.Task:
    properties:
      created_at:
        type: string
      description:
        type: string
      due_date:
        type: string
      id:
        type: integer
      status:
        type: string
      title:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: Simple Todo API with Gin, GORM, MySQL, Swagger
  title: Todo API
  version: "1.0"
paths:
  /deleteTask/{id}:
    delete:
      description: Delete a task by its id (JWT required)
      parameters:
      - description: Task id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Task deleted successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid task id
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Task not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to delete task
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Delete a task
      tags:
      - tasks
  /login:
    post:
      consumes:
      - application/json
      description: Authenticate user with username and password
      parameters:
      - description: User login credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Invalid username or password
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: Creates a new user
      parameters:
      - description: User registration data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controllers.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid input or username already exists
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Server error (failed to hash password)
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - Auth
  /task:
    post:
      consumes:
      - application/json
      description: Add a new task (JWT required)
      parameters:
      - description: Task input
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/controllers.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Task'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create a new task
      tags:
      - tasks
  /tasks:
    get:
      description: Retrieve all tasks from database (no filter) (JWT required)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Task'
            type: array
      security:
      - BearerAuth: []
      summary: Get all tasks
      tags:
      - tasks
  /tasks/{id}:
    get:
      description: Retrieve a single task by its ID (JWT required)
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Task'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get a task by ID
      tags:
      - tasks
  /tasksByFilter:
    get:
      description: Retrieve all tasks with optional filters (status, due_date) (JWT
        required)
      parameters:
      - description: Filter by status (pending, in-progress, completed)
        in: query
        name: status
        type: string
      - description: Filter by due date (YYYY-MM-DD)
        in: query
        name: due_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Task'
            type: array
        "400":
          description: Invalid due_date format
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to fetch tasks
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get all tasks
      tags:
      - tasks
  /updateTasks/{id}:
    put:
      consumes:
      - application/json
      description: Replace all fields of a task by its ID. (JWT required)
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated Task input
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/controllers.UpdateTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Task'
        "400":
          description: Invalid request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Task not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to update task
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Update a task
      tags:
      - tasks
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
